- src/PlugKeyRing/plugKeyRing.test.ts
- src/PlugWallet/index.ts
Added principal to state and remove getter method.
This allows front-end to use it without having to resort to weird toJSON setups.
> Removed principal getter, added principal to state

- src/PlugKeyRing/index.ts
- src/PlugKeyRing/utils.ts
- src/PlugWallet/index.ts
- Added `sign` method for both keyring and wallet
- Exposed `getPublicKey` method.
- Fixed subaccount validation
> IC PAPI - Keyring sign method

- package.json
- src/PlugKeyRing/index.ts
- src/PlugWallet/index.ts
- src/utils/crypto/secpk256k1/identity.ts
Add the possibility of generate a pemfile to export plug identity to dfx
> feature: export pemfile from wallet [ch23448]

- package.json
- src/PlugKeyRing/index.ts
- src/PlugKeyRing/plugKeyRing.test.ts
- src/PlugKeyRing/utils.ts
- Changed setCurrentPrincipal to receive a number instead of a wallet
For easier management in FE
> Switched set current principal to use a numbner instead of a wallet

- package.json
- src/PlugWallet/index.ts
- src/idls/xtc.did.ts
- src/utils/dfx/constants.ts
- src/utils/dfx/token/index.ts
- src/utils/dfx/token/methods.ts
- Fixed infinite recursion on getBalance
> Fix: get balance infinite recursion

- src/PlugKeyRing/index.ts
- src/PlugWallet/index.ts
- src/idls/xtc.did.ts
- src/interfaces/xtc.ts
- src/utils/dfx/token/methods.ts
- src/utils/dfx/token/xtcMethods.ts
> Feature v3 add burn to keyring ch23627

- package.json
- src/PlugKeyRing/plugKeyRing.test.ts
- src/PlugWallet/index.ts
- src/constants/tokens.ts
- src/interfaces/ext.ts
- yarn.lock
- Added XTC to registered token list on first balance call
> Added XTC on first balance call

- src/PlugKeyRing/index.ts
- src/PlugKeyRing/plugKeyRing.test.ts
- src/PlugWallet/index.ts
- src/errors.ts
- Added `transferNFT({ subAccount: number, to: string, id: bigint })` method to keyring
- Added corresponding method on wallet and added tests.
> IC Punks - Transfer NFT

- package.json
- src/PlugKeyRing/index.ts
- src/PlugWallet/index.ts
- src/constants/tokens.ts
- src/utils/dfx/history/xtcHistory.ts
- Added assets to wallet attributes.
- Adde ICP and XTC as default assets with 0
- Added kyashu update calls
> bump version. Added asset caching. Added kyashu update calls

- package.json
- src/PlugKeyRing/plugKeyRing.test.ts
- src/utils/dfx/index.ts
- src/utils/signature/index.ts
- src/utils/storage/index.ts
- yarn.lock
Removed dotenv and added depndency injection in tests. Removed text encoder usages and replaced it with a shim
> Mobile Required Fixes

- package.json
- src/utils/dab.ts
- src/utils/dfx/constants.ts
- src/utils/dfx/index.ts
- src/utils/dfx/wrappedFetch.ts
- Change IC_HOST to Cap seeder proxy url
> Modified host url and bumped minor version

- package.json
- src/utils/dfx/constants.ts
- src/utils/dfx/history/xtcHistory.ts
- Change proxy url to mainnet
- Added `pid` to kyasshu's update call
> Change proxy url to mainnet, fix kyasshu request

- src/PlugKeyRing/index.ts
- src/PlugKeyRing/plugKeyRing.test.ts
- src/PlugWallet/index.ts
- src/constants/tokens.ts
- src/idls/dip20.did.ts
- src/interfaces/dip20.ts
- src/interfaces/ext.ts
- src/utils/dfx/token/dip20Methods.ts
- src/utils/dfx/token/extMethods.ts
- src/utils/dfx/token/index.ts
- src/utils/dfx/token/methods.ts
- src/utils/dfx/token/xtcMethods.ts
- Make a big refactor to add standars easier
- Implement dip20 standard
> feat: dip20 implementation

- package.json
- src/utils/dfx/history/cap.ts
- src/utils/dfx/history/rosetta.ts
- yarn.lock
- Update cap to 0.0.7
- Fixed integration
-  Parsed pids
-  fixed ICP integration
> Update cap to 0.0.7.

- src/PlugKeyRing/index.ts
- src/utils/crypto/identity.ts
- Added empty storage set to fix firefox storage. 
- Fixed pem import by serializing public key to raw bytes.
> 0.4.2 Fixes

- package.json
- src/PlugKeyRing/index.ts
- src/PlugWallet/index.ts
- src/utils/dab.ts
- yarn.lock
use getCachedUserNFTs from dab-js
> feat: use getCachedUserNFTs

- package.json
- src/PlugKeyRing/index.ts
- src/PlugWallet/index.ts
- src/utils/dfx/history/rosetta.ts
- src/utils/dfx/history/xtcHistory.ts
- src/utils/dfx/ledger/methods.ts
- src/utils/dfx/token/dip20Methods.ts
- src/utils/dfx/token/extMethods.ts
- src/utils/dfx/token/index.ts
- src/utils/dfx/token/methods.ts
- src/utils/dfx/token/xtcMethods.ts
> feat: parse numbers into tokens

- package.json
- src/utils/dfx/history/xtcHistory.ts
- Fix XTC decimals to allow proper parsing in front end
> Fixed xtc decimals and bumped patch version

- src/errors.ts
Changes nft send error message.
> Fixed error message for nft transfers

- package.json
- src/utils/dfx/history/cap.ts
- yarn.lock
CAP encode BigInts using NAT from candid which in the deep use lebEncode, so we need to lebDecode to make it works
> fix: parse amounts received

- package.json
- src/idls/dip20.did.ts
- src/idls/wicp.did.ts
- src/interfaces/dip20.ts
- src/interfaces/wicp.ts
- src/utils/dfx/token/dip20Methods.ts
- Changed ok/err for Ok/Err in DIP20
- Changed getLogo for logo in WICP
> Update DIP20 interface for Ok/Err and WICP logo method

- package.json
- src/PlugWallet/index.ts
- src/utils/dfx/token/index.ts
Add the possibility of remove registered tokens
> feat: remove token

- src/PlugKeyRing/index.ts
- src/PlugWallet/index.ts
- Added remove token to keyring
- Removed token from assets as well
> Fix: Remove token

- package.json
- src/PlugKeyRing/index.ts
- src/PlugKeyRing/plugKeyRing.test.ts
- src/PlugWallet/index.ts
- src/constants/tokens.ts
- src/utils/crypto/binary.ts
- src/utils/dfx/history/cap.ts
- src/utils/dfx/history/rosetta.ts
- src/utils/dfx/token/index.ts
- src/utils/dfx/token/methods.ts
- Refactored how ICP balance is fetched and implemented rosetta API balance call (TODO: Implement whole rosetta API Class)
- Added missing fields to ICP to prep it to become a standard token when token storage refactor is implemented.
- Minor fixes for values that even though are currently unused could bring confusions to newcomers.
> Fix balance issues and add single token balance requests

- package.json
- src/PlugKeyRing/index.ts
- src/constants/version.ts
- src/interfaces/storage.ts
- src/utils/storage/utils.ts
- src/utils/version.ts
- yarn.lock
Every time a new version of PlugController is deployed, controller gonna check if some update should be done on the storage
https://app.shortcut.com/terminalsystems/story/24864/refactor-version-storage-schema
> feat: implement storage update handler

- package.json
- src/PlugKeyRing/index.ts
- src/PlugWallet/index.ts
Added accountID formatting to send ICP, removed incorrect conditional…, bumped patch version
> Fix ICP send

- package.json
- src/utils/dfx/history/xtcHistory.ts
> Fixed post request

- package.json
- src/constants/version.ts
- yarn.lock
Update to dab-js 1.2.0 with newest dip20 interface
> Fix: DIP20 send 

- package.json
- src/constants/version.ts
- src/utils/dfx/history/cap.ts
- Fixed swap serialization. 
- Update patch version
> Fix: Swap token serialization

- package.json
- src/utils/dfx/history/cap.ts
- Added LastEvaluatedKey check to query kyasshu until now new data is found
- Fixed sonic swap token information serialization by taking addresses from the details fields instead of the pair id.
> Fix: Sonic Swaps + LastEvaluatedKey

- src/PlugKeyRing/index.ts
- Added refresh param to `getNFTs`
> Added refresh option to getNFTs

- package.json
- src/utils/dfx/history/cap.ts
- Construct params and pass in as parameter instead of serializing them in the query params.
> Tentative Fix: Missing activity

- package.json
- src/PlugWallet/index.ts
- src/constants/version.ts
- src/idls/icns_registry.did.ts
- src/idls/icns_resolver.did.ts
- src/interfaces/icns_registry.ts
- src/interfaces/icns_resolver.ts
- src/interfaces/plug_wallet.ts
- src/utils/dfx/icns/index.ts
Added ICNSAdapter module. Added icnsNames to PlugWallet and serialized them in the getNFTs call
> [WIP] ICNS Integration

- src/constants/version.ts
- yarn.lock
> Updated lock and version files

- package.json
- src/PlugWallet/index.ts
- yarn.lock
Installed dab-js 1.3.2 including ext nft token transfer fee fix
> Fix: Send EXT NFT

- package.json
- src/constants/version.ts
- src/utils/storage/update_handlers/v0.16.8.ts
- src/utils/storage/utils.ts
Added storage update wiping null asset and replacing it with proper ICP token
> Fix: canisterId is invalid

- package.json
- src/constants/version.ts
- src/utils/dfx/icns/index.ts
Added record resetting to reverse resolution name setting.
> Feature: Reset record on reverse resolution set

- package.json
- src/utils/dfx/icns/index.ts
- Removed account ID setting on reverse resolution change.
- Change PID before switching names
> [Fix] ICNS Reverse resolution setting behavior

- package.json
- src/constants/version.ts
- src/utils/dfx/history/cap.ts
When dealing with liquidity events, add special information for FE to serialize it correctly
> Fix: Sonic Liquidity Activity

- package.json
- src/PlugWallet/index.ts
- src/utils/dfx/constants.ts
- src/utils/dfx/wrappedFetch.ts
- Makes NFT query refetch from ic natively in case kyasshu fails
- Fixes plug-proxy fallback algorithm
> Fix: Proxy Fallback

- src/PlugKeyRing/index.ts
- src/PlugWallet/index.ts
- src/interfaces/cap.ts
- src/utils/dab.ts
- src/utils/dfx/history/cap/index.ts
- src/utils/dfx/history/cap/sonic.ts
- src/utils/dfx/wrappedFetch.ts
- src/utils/storage/utils.ts
> feat: get all canisterInfo before formatting

- package.json
- src/PlugKeyRing/index.ts
- src/PlugKeyRing/modules/NetworkModule/Network.ts
- src/PlugWallet/index.ts
- src/interfaces/token.ts
> Fix: Token images

- src/PlugKeyRing/index.ts
- src/PlugKeyRing/modules/NetworkModule/Network.ts
- src/PlugKeyRing/modules/NetworkModule/index.ts
- src/constants/version.ts
- src/utils/storage/update_handlers/v0.19.3.ts
- src/utils/storage/utils.ts
- tsconfig.json
- Added storage handler for version 0.19.3 to map registered custom tokens to new network structure.
> Fix: 0.19.3 storage handler

- package.json
- src/PlugWallet/index.ts
* Using index of token to filter the collection. Solves an issue when filtering collection in the response
> Fix/Transfer NFT filter

- package.json
- src/PlugWallet/index.ts
- src/constants/version.ts
Addes removeToken method to PlugWallet
> Add removeToken method to PlugWallet

- src/PlugKeyRing/index.ts
- src/constants/version.ts
- Removed duplicated imports
- Updated version file
> Fix: Removed duplicated imports

- src/PlugKeyRing/index.ts
- src/PlugKeyRing/modules/NetworkModule/Network.ts
- src/PlugWallet/index.ts
- src/errors.ts
Summary
- Change registerNFT response to return the registered NFT only
- Add error on repeated registered NFT
> Change response to return the registered NFT only

- package.json
- src/PlugKeyRing/index.ts
- src/PlugKeyRing/interfaces.ts
- src/constants/version.ts
- src/utils/account/constants.ts
- src/utils/identity/identityFactory.ts
We need the ability of create an account from secretKey for some futures features
> feat: implement importAccounFromSecretKey

- package.json
- yarn.lock
Updated dab-js to 1.5.1 incl canister id icp fix
> Fix: send ICP to canisterId

- package.json
- src/PlugWallet/index.ts
- src/constants/version.ts
- yarn.lock
- Added latest dab-js to make standards capitalized
- Add a `toUpperCase` in case kya is outdated
> Fix: Missing NFTs
